{
 "title": "nextractplus_v41_energy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "servername",
    "label": "servername",
    "query": "SHOW TAG VALUES WITH KEY = \"servername\""
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "# Range included Zero" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Range Zoomed-In to show the more datails"
   }
  },
  {
   "title": "Electrical Power Consumption in Watts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Electrical Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    },
    {
     "alias": "Electrical Power Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  },
  {
   "title": "Electrical Power Consumption in Watts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Electrical Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  },
  {
   "title": "All CPU Probe  Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_cpu_name]]",
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "temp_processor",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  },
  {
   "title": "All CPU Probe  Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_cpu_name]]",
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "temp_processor",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  },
  {
   "title": "Room Inlet Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Room Inlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp_room",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Room Inlet Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Room Inlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp_room",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Planar and Room Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_mb_name]]",
     "groupBy": [
      { "params": [ "mb_name" ], "type": "tag" }
     ],
     "measurement": "temp_planar",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  },
  {
   "title": "System Planar Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_mb_name]]",
     "groupBy": [
      { "params": [ "mb_name" ], "type": "tag" }
     ],
     "measurement": "temp_planar",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature spread",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_cpu_name]]",
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "temp_processor",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$servername$/" }
     ]
    }
   ]
  }
 ]
}